//
// Created by appuprakhya on 8/10/22.
//

#ifndef QUANTLIB_EXAMPLES_INTERPOLATION_ALL_HPP
#define QUANTLIB_EXAMPLES_INTERPOLATION_ALL_HPP
void linearInterpolationExample();
#endif //QUANTLIB_EXAMPLES_INTERPOLATION_ALL_HPP
