//
// Created by appuprakhya on 14/9/22.
//

#ifndef QUANTLIB_EXAMPLES_VANILLAOPTIONS_EX_ALL_HPP
#define QUANTLIB_EXAMPLES_VANILLAOPTIONS_EX_ALL_HPP
void test_vanilla_option_pricing();
#endif //QUANTLIB_EXAMPLES_VANILLAOPTIONS_EX_ALL_HPP
