//
// Created by appuprakhya on 14/9/22.
//

#ifndef QUANTLIB_EXAMPLES_RANDOMNUMBERGENERATOREXALL_HPP
#define QUANTLIB_EXAMPLES_RANDOMNUMBERGENERATOREXALL_HPP
void testMersenneTwisterUniformRng();
void testRandomSeqGenUsingMTRng();
#endif //QUANTLIB_EXAMPLES_RANDOMNUMBERGENERATOREXALL_HPP
